# Generated by Django 5.1.4 on 2025-01-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='personas',
        ),
    ]
