# Generated by Django 5.1.4 on 2025-01-09 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personas', '0003_remove_persona_id_persona_id_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id_identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_identificacion', models.BigIntegerField(unique=True)),
                ('lugar_expedicion', models.CharField(max_length=255)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identificaciones', to='gestion_personas.persona')),
            ],
            options={
                'db_table': 'identificacion',
            },
        ),
    ]
