# Generated by Django 5.1.4 on 2025-01-15 19:31

import django.db.models.deletion
import gestion_personas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personas', '0004_identificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='ProcesoContractual',
            fields=[
                ('id_proceso', models.AutoField(primary_key=True, serialize=False)),
                ('numero_sipse', models.CharField(max_length=255)),
                ('fecha_de_solicitud', models.DateField()),
                ('fecha_de_vencimiento', models.DateField()),
                ('abogado_a_cargo', models.CharField(max_length=255)),
                ('cdp', models.CharField(max_length=255)),
                ('crp', models.CharField(max_length=255)),
                ('numero_de_no_hay', models.CharField(max_length=255)),
                ('riesgo', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Proceso Contractual',
                'verbose_name_plural': 'Procesos Contractuales',
                'db_table': 'proceso_contractual',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.AlterModelOptions(
            name='identificacion',
            options={'verbose_name': 'Identificación', 'verbose_name_plural': 'Identificaciones'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AddField(
            model_name='identificacion',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=2),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='numero_identificacion',
            field=models.BigIntegerField(unique=True, validators=[gestion_personas.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('numero_contrato', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('meses_antiguedad', models.IntegerField(validators=[gestion_personas.models.validate_positive])),
                ('honorarios_mes', models.DecimalField(decimal_places=2, max_digits=10, validators=[gestion_personas.models.validate_positive])),
                ('objeto_contrato', models.TextField()),
                ('numero_obligaciones', models.IntegerField(validators=[gestion_personas.models.validate_positive])),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='gestion_personas.persona')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='ProcesoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_personas', to='gestion_personas.persona')),
                ('id_proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_personas', to='gestion_personas.procesocontractual')),
            ],
            options={
                'verbose_name': 'Proceso Persona',
                'verbose_name_plural': 'Procesos Personas',
                'db_table': 'proceso_personas',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='id_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='gestion_personas.rol'),
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id_subgrupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subgrupo', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgrupos', to='gestion_personas.area')),
            ],
            options={
                'verbose_name': 'Subgrupo',
                'verbose_name_plural': 'Subgrupos',
                'db_table': 'subgrupos',
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='subgrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='gestion_personas.subgrupo'),
        ),
    ]
